In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int64'

In [9]:
a.itemsize

8

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray



---



In [13]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [14]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
b.ndim

2

In [17]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [18]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
c.ndim

2



---



In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

uninitialized, output may vary

---



In [23]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])



---



1d array

In [25]:
a = np.arange(6)

In [28]:
print(a)

[0 1 2 3 4 5]


2d array

In [29]:
b = np.arange(12).reshape(4, 3)

In [30]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


3d array

In [31]:
c = np.arange(24).reshape(2, 3, 4)

In [32]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]




---



In [33]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [34]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]




---



In [36]:
a = np.array([20, 30, 40, 50])

In [37]:
b = np.arange(4)

In [38]:
b

array([0, 1, 2, 3])

In [40]:
c = a - b

In [41]:
c

array([20, 29, 38, 47])

In [42]:
b**2

array([0, 1, 4, 9])

In [43]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [44]:
a < 35

array([ True,  True, False, False])



---

#### * : elementwise product / @, dot : matrix product

In [45]:
A = np.array([[1, 1],
              [0, 1]])

In [46]:
B = np.array([[2, 0],
              [3, 4]])

In [47]:
A * B

array([[2, 0],
       [0, 4]])

In [48]:
A @ B

array([[5, 4],
       [3, 4]])

In [49]:
A.dot(B)

array([[5, 4],
       [3, 4]])



---



In [50]:
b = np.arange(12).reshape(3, 4)

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

axis=0 : column

In [53]:
b.sum(axis=0)

array([12, 15, 18, 21])

axis=1 : row

In [54]:
b.min(axis=1)

array([0, 4, 8])